// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Config injetada pelo backend ao servir /flow (evita 401) ou variáveis de build
declare global {
  interface Window {
    __SUPABASE_CONFIG__?: { supabase_url: string; supabase_anon_key: string };
  }
}
const _config = typeof window !== 'undefined' ? window.__SUPABASE_CONFIG__ : undefined;
const SUPABASE_URL = _config?.supabase_url || import.meta.env.VITE_SUPABASE_URL || 'https://gwjcgzeybqiyqezuswpt.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = _config?.supabase_anon_key || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'placeholder-key';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Criar cliente com valores padrão para evitar erro de inicialização
// O Flow Editor não precisa do Supabase, então valores placeholder são aceitáveis
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});